repos:
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        args: [--line-length=120]
        exclude: ^app/

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [ '--config=.flake8' ]
        exclude: ^app/

  - repo: https://github.com/pycqa/isort
    rev: 6.1.0
    hooks:
      - id: isort
        args: [--profile=black, --line-length=120]
        exclude: ^app/


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-executables-have-shebangs
        exclude: ^app/
      - id: end-of-file-fixer
        exclude: ^(tests/data/.*\.TextGrid|app|.*\.vtt/)$  # don't run on TextGrid files or app/
        exclude: ^app/
        exclude: ^tests/data/
      - id: mixed-line-ending
        exclude: ^app/
      - id: trailing-whitespace
        exclude: ^app/
        exclude: ^tests/data/
